name: Release

on:
    push:
        branches:
            - master

jobs:
    release-and-test:
        name: Publish
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Env
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Cache node modules
              uses: actions/cache@v1
              env:
                  cache-name: v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install Deps
              run: npm install

            - name: Test
              run: npm run test

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              id: semantic
              with:
                  branch: master
                  extra_plugins: |
                      @semantic-release/git
                      @semantic-release/changelog
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
